import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE

        'pt_PT': {
          "All Item": "Todos os items",
          'Please check your internet connection':
              'Por favor verifique a sua conexão',
          'My Address 1': 'Minha morada 1',
          'a long title': 'título longo',
          'O meu perfil': 'o meu perfil',
          "Nome de Utilizador": "Nome de Utilizador",
          "As minhas morada": "As minhas morada",
          "Adicionar Morada": "Adicionar Morada",
          "Contacto": "Contacto",
          "Dados Privados": "Dados Privados",
          "Save": "Guardar",
          "Cancel": "Cancelar",
          "Something went wrong": "Algo correu mal",
          "Descrição Produto": "Descrição Produto",
          "Selecione uma opção": "Selecione uma opção",
          "Selecione uma opção ingrediente extra":
              "Selecione uma opção ingrediente extra",
          "Enter notes": "Enter notes",
          "Introduza a sua nota": "Introduza a sua nota",
          "Notas": "Notas",
          "Total Price": "Preço total",
          "Adicionar": "Adicionar",
          "Morada": "Morada",
          "A tua morada": "A tua morada",
          "Morada do utilizador": "Morada do utilizador",
          "Hora de Entrega": "Hora de Entrega",
          "Agora": "Agora",
          "Detalhes do Pedido": "Detalhes do Pedido",
          "Delete": "Eliminar",
          "Add One": "Adicionar 1",
          "Total": "Total",
          "Loading": "A carregar",
          "Fazer pedido": "Fazer pedido",
          "Select Time Slot To Deliver": "Selectione a hora de entrega",
          "delivery_date": "",
          "time_slot": "Hora de entrega",
          "Categorias": "Categorias",
          "Ver todas": "Ver todas",
          "Lista de comida": "Lista de comida",
          "Categories": "Categorias",
          "Search Product": "Procurar produto",
          "Agendar entrega": "Agendar entrega",
          "Agendar": "Agendar",
          "Today": "Hoje",
          "SignUp": "Registar",
          "First Name Can\'t be empty": "Primeiro nome não pode ser vazio",
          "Enter First Name": "Insira Primeiro nome",
          "First Name": "Primeiro nome",
          "Last Name Can\'t be empty": "Último nome não pode ser vazio",
          "Enter Last Name": "Insira último nome",
          "Last Name": "Último nome",
          "Email Can\'t be empty": "E-mail não pode ser vazio",
          "Enter your email": "Insira o e-mail",
          "Email": "E-mail",
          "Phone No Can\'t be empty": "Telefone não pode ser vazio",
          "Enter your phone number": "Insira telefone",
          "Telephone": "Telefone",
          "Enter Password": "Insira password",
          "Password must be  at least 6 characters":
              "A password tem que ter pelo menos 6 caracteres",
          "Enter your Password": "Insira password",
          "Password": "Senha",
          "Retype Password": "Volte a inserir password",
          "Password Missmatch": "Palavra passe não correspondem",
          "Sign Up": "Registar",
          "LogIn": "Login",
          "verify provide otp": "verificar fornecer otp",
          "verify_otp_sent": "verify_otp_sent",
          "Confirm": "Confirmar",
          "Enter email": "Insira e-mail",
          "Enter your email or phone": "Insira e-mail",
          "Forgot password?": "Esqueceu password",
          "Email or Password is not valid": "Email ou password inválidos",
          "Forgot your password": "Esqueci-me da password",
          "Insert Your Email": "Insira o email",
          "Next": "Próximo",
          "Redefine password": "Redefinir password",
          "Provide your email": "Insira email",
          "Code Can\'t be empty": "Código inválido",
          "Enter your verification code check email":
              "Insira código de verificação",
          "Verification Code": "Código de verificação",
          "Change Password": "Alterar password",
          "Can\'t be empty": "Não pode ser vazio",
          "casa": "casa",
          "Nome da modrao": "Morada",
          "Localização Atual": "Localização Atual",
          "Morada/Rua": "Morada/Rua",
          "Número": "Número",
          "Codigo postal": "Codigo postal",
          "Estado Can\'t be empty": "Estado Can\'t be empty",
          "Enter your Estado": "Estado",
          "Estado": "Estado",
          "Cidade No Can\'t be empty": "Cidade não pode ser vazio",
          "Enter your Cidade": "Insira cidade",
          "Cidade": "Cidade",
          "Continue": "Continuar",
          "Registar": "Registar",
          "Login": "Login",
          "Remove Account": "Remover conta",
          "No item found": "Item não encontrado",
          "Payment successfull order completed": "Pedido concluído com sucesso",
          "Payment failed order incomplete":
              "Falha no pagamento pedido incompleto",
          "My Orders": "minhas ordens",
          "Order History": "Histórico de pedidos",
          "Click to check your order": "Clique para verificar seu pedido",
          "No items found": "No items found",
          "Yes": "Sim",
          "No": "Não",
          "Do you want to sign out?": "Deseja sair?",
          "Do you want to Remove your Account?": "Deseja remover sua conta?",
          "Old Password": "Senha Antiga",
          "New Password": "Nova Senha",
        }
      };
}
